### ISSUE TITLE
Can this framework set ime-varying weights for assets in the portfolio? 

### ISSUE THREAD

**Issue by yookiezhou** [ssantoshp/Empyrial#119]
Hi,

According to the documentm, seems when backtesting, the weights of assets are fixed. Can the framework allow time-varying weights? For example, we can input different weights for each time point, in this case, we can combine the stocks selection strategy (some stocks into the portfolio, some stocks out of the portfolio) with the portfolio performance test. If you can set up this, that would be very helpful.

**Comment by ssantoshp** [comment]
Yes, I'll add that to my feature list and work on it, thanks for the feedback!
