### ISSUE TITLE
Hard-coded Risk-free rate

### ISSUE THREAD

**Issue by karim1104** [ssantoshp/Empyrial#23]
The risk-free rate is hard-coded in empyrial.py in line 197 (rf = 0.0).
Please change it to a variable so we can adjust it as needed.

**Comment by ssantoshp** [comment]
Hey,

You can change that by doing ```empyrial(your_portfolio, rf=0.1)``` for example.

Hope it helps

**Comment by karim1104** [comment]
Hi Santosh,
It worked as a code, but it broke the Sharpe Ratio.
When I use "empyrial(portfolio, rf=0.0)", I get a Sharpe Ratio of 1.33 which is realistic.
When I use "empyrial(portfolio, rf=0.01)", I get a Sharpe Ratio of -7.06 which is unrealistic.

**Comment by ssantoshp** [comment]
Can you share the whole code please so I can try it out?

**Comment by karim1104** [comment]
start_date = datetime.datetime(2010, 1, 1)
df = pd.read_csv('Portfolio1.csv')

x = df.to_string(header=False,
                  index=False,
                  index_names=False).split('\n')
names = [','.join(ele.split()) for ele in x]
portfolio = Engine(    
                  start_date= start_date, 
                  portfolio= names, 
                  benchmark = ["SPY"] 
                  
)

empyrial(portfolio, rf=0.01)

**Comment by ssantoshp** [comment]
I think this is because rf refers to the DAILY risk-free rate. Does it help?

**Comment by ssantoshp** [comment]
Ok just modified it a little bit with the new version (1.5.5). 

Should work now as you can see in this notebook: https://colab.research.google.com/drive/1CKMf1YudMsf8ryD5tOYddVU0fRaQJnWx?usp=sharing

The sharpe ratio is credible. Is it fine?

**Comment by karim1104** [comment]
Confirmed it's working fine. Issue is fixed in version 1.5.5.

Thanks!
