### ISSUE TITLE
RemoteDataError: No data fetched using 'YahooDailyReader'

### ISSUE THREAD

**Issue by ssantoshp** [ssantoshp/Empyrial#29]
### Discussed in https://github.com/ssantoshp/Empyrial/discussions/27

<div type='discussions-op-text'>

<sup>Originally posted by **karim1104** July  3, 2021</sup>
Starting July 1, I'm getting the error "RemoteDataError: No data fetched using 'YahooDailyReader'". I've tried it in different Python environments (3.6, 3.8, 3.9).
It seems like a Pandas DataReader issue (https://github.com/pydata/pandas-datareader/issues/868)
How can we resolve this? I have a subscription to FMP, is there a way I use instead of Yahoo Finance?</div>

**Comment by ssantoshp** [comment]
Hi,

Are you sure you are using Empyrial 1.8.3 (this one fixes the bug)? If yes and you still get this error, I'd like to see the code you are running in order to reproduce the error, please 🙏

**Comment by ssantoshp** [comment]
@karim1104 ?

**Comment by karim1104** [comment]
Sorry Santosh, I must have missed your comment. I'll test version 1.9.0 and revert with feedback.

**Comment by ssantoshp** [comment]
No problem :) By the way, there was a bug on 1.9.0 so you should try with 1.9.1

**Comment by karim1104** [comment]
Upgraded Empyrial to version 1.9.1 and tested in Python 3.9.5, everything seems to be working great.
Thank you very much Santosh!

**Comment by ssantoshp** [comment]
Nice :)
