### ISSUE TITLE
Support for custom data, or data from other exchanges

### ISSUE THREAD

**Issue by suvojit-0x55aa** [ssantoshp/Empyrial#31]
**Is your feature request related to a problem? Please describe.**
I want to analyze portfolio in other exchanges.

**Describe the solution you'd like**
Ability to provide other exchange data.

**Comment by ssantoshp** [comment]
Hi @suvojit-0x55aa,

There is actually a way to use custom data but the problem is that it is impossible to use rebalancing if you use custom data. That's the problem. But, I'm curious to know why you would like to use custom data and where is your data from?

Best 😄

**Comment by suvojit-0x55aa** [comment]
@ssantoshp I wanted to use it with NSE data.

**Comment by ssantoshp** [comment]
@suvojit-0x55aa Ok, yeah I get it. So, if you want to use custom data you can't rebalance, that's the problem, sorry. But you can also access Indian stock with yfinance, right?

**Comment by ma-ji** [comment]
Hi, thanks for this great work! Can you give a toy example about how to use customized data?
