### ISSUE TITLE
Annual return in bar diagram or similar

### ISSUE THREAD

**Issue by markthebault** [ssantoshp/Empyrial#37]
First of all your project is Awesome !!!!

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I would like to see easily for each year what is my % return, Ideally, it will be a bar chart.

**Describe alternatives you've considered**
In the monthly return add a new column for the annual return

**Additional context**

<img width="1401" alt="Screenshot 2021-08-03 at 12 57 20" src="https://user-images.githubusercontent.com/3846664/128004400-b39b5b42-d704-4291-a7d2-ad3f2df7bd2a.png">

**Comment by markthebault** [comment]
I created a PR here: https://github.com/ssantoshp/Empyrial/pull/38

**Comment by ssantoshp** [comment]
Thanks for contributing! Awesome work, man 😺
