### ISSUE TITLE
Custom weighting not working

### ISSUE THREAD

**Issue by NelsonMaty** [ssantoshp/Empyrial#39]
**Describe the bug**
Asset allocation is equally weighted when no optimisation method is provided.

**To Reproduce**
Use the documented [example](https://empyrial.gitbook.io/empyrial/optimization/custom-allocation) for custom asset allocation.

```
portfolio = Engine(
      start_date = "2018-01-01",
      portfolio= ["BABA", "PDD", "KO", "AMD","^IXIC"], 
      weights = [0.1, 0.3, 0.15, 0.25, 0.2], #custom weights
)

```

**Expected behavior**
`portfolio.weights` equals to `[0.1, 0.3, 0.15, 0.25, 0.2]`

**Actual behavior**
`portfolio.weights` equals to `[0.2, 0.2, 0.2, 0.2, 0.2]`

**Comment by NelsonMaty** [comment]
I believe this issue was introduced on this PR: https://github.com/ssantoshp/Empyrial/pull/35

**Comment by ssantoshp** [comment]
Hi ✋ 

Thanks for reporting this issue. I just fixed it, it should be fine now. You can check it here: https://colab.research.google.com/drive/1dygKh3LsmBEtevSXLCG2h_8bvpSACbYt?usp=sharing

**Comment by NelsonMaty** [comment]
It's working perfectly, thanks!! 😄
