### ISSUE TITLE
add daily and weekly rebalance period

### ISSUE THREAD

**Issue by abhinavslohiya** [ssantoshp/Empyrial#62]
I committed a change before for adding daily and weekly rebalancing. The commit got approved and implemented but I still cannot use that feature. I guess we would need further modifications in the empyrial.py file.

**Comment by ssantoshp** [comment]
I just updated the library. Make sure to install the new version by doing:

'''pip install empyrial==2.0.0"


However as you can see it here: https://colab.research.google.com/drive/1lgVkdshq0WsZKdYURZCk7FvJucspmWXe?usp=sharing

It seems that there are some problems with the daily and weekly rebalancing...
