### ISSUE TITLE
Test example is broken

### ISSUE THREAD

**Issue by dev590t** [ssantoshp/Empyrial#64]
**Describe the bug**
Empyrial/test/rebalance_test.py  and Empyrial/test/optimizer_test.py doesn't run.

**To Reproduce**
```
(base) pdm run python Empyrial/test/rebalance_test.py 
Traceback (most recent call last):
  File "Empyrial/test/rebalance_test.py", line 14, in <module>
    empyrial(portfolio, rebalance = True)
TypeError: empyrial() got an unexpected keyword argument 'rebalance'
(base) pdm run python Empyrial/test/optimizer_test.py 
Traceback (most recent call last):
  File "Empyrial/test/optimizer_test.py", line 9, in <module>
    optimizer(portfolio, "EF")
NameError: name 'optimizer' is not defined
```
I can't find the function optimizer in the code, and the parameter rebalance in the header of function empyrial

**Comment by ssantoshp** [comment]
Hello,

Yes, the optimizer function has been removed. 

Here is the doc where you will see how to optimize and rebalance your portfolio now: https://empyrial.gitbook.io/empyrial/

Hope it helps!

**Comment by dev590t** [comment]
@ssantoshp  Thanks
