### ISSUE TITLE
Error when rebalancing with only one stock

### ISSUE THREAD

**Issue by atobiese** [ssantoshp/Empyrial#65]
Hi, 
I have tried to reproduce test results and simulated one single stock over time by forcing the weight distribution as shown below: 
      tickers = ["stock1", "stock2"]
      weights_new_ = [1.0, 0.0]
no optimizer is used, so just using the quantstats calculations of ratios and returns. 
In the next example, we do the same but with a yearly rebalancer. The thing here is that the results should be exactly the same. 
There seems to be a slight error in the returns calculations over time, which turns out to be bigger with more rebalancing. 

I will have some more look at it, and update if I find the bug. Btw great work!

**Comment by ssantoshp** [comment]
Hey,

Sorry, for the late reply?
There is no purpose in rebalancing only one stock. The weight will stay the same. 
Hope it helps!

**Comment by atobiese** [comment]
Hi, of course, but the point I was trying to make is that there is a math error. The end value is NOT the same here. This means that when using more than one stock), the rebalancing will create large errors. 
The test for this is simply rebalancing with two stocks, where the second weight is zero. The result should be exactly the same, since a perfentage of zero is zero. So since this result is different than the single stock, the math is not correct.

**Comment by ssantoshp** [comment]
Sorry!! My fault, I misinterpreted the issue. If you find the bug, pin me! I'll also look at the code to see where is the problem coming from 😟 
Thanks for reporting this issue!

**Comment by atobiese** [comment]
I haven't looked at the code for a while, but it could be the precision of the calculations in pypfopt, resulting in rounding erros outside after several balancers. Errors grow fast as I remember. May need higher precision. Could be a summation error etc. I'll have a look if I get time. Regards

**Comment by ssantoshp** [comment]
This pull request solved it; https://github.com/ssantoshp/Empyrial/pull/72
You can install Empyrial 2.0.1 and it should work!
