### ISSUE TITLE
Graph styling

### ISSUE THREAD

**Issue by rgleavenworth** [ssantoshp/Empyrial#69]
Is there a way to override the default styling parameters used in your tearsheet? I understand that most of the styling is inherited from quantstats. Anyway you can suggest how to change things like facecolor, linewidth, etc?

**Comment by ssantoshp** [comment]
Sorry for the (very) late reply. 

For the moment, there are now ways to modify that with Empyrial. I checked Quantstats source code and it doesn't seem like it provides a lot of flexibility in terms of styling...

**Comment by rgleavenworth** [comment]
Yeah, I went through the qs code as well and the author has hardcoded the styling in the code. I'm going to create a branch and submit a pull request there to see if we can submit styling through a function call and will contact you if/once that is accepted.

**Comment by ssantoshp** [comment]
Once you do it, tell me! I'll do the changes for sure ;)
