### ISSUE TITLE
assets value / non-stock based portfolio?

### ISSUE THREAD

**Issue by andrew521** [ssantoshp/Empyrial#74]
Wondering if Empyrial can be used with a non-stock based portfolio. The example in the docs is like this:

from empyrial import empyrial, Engine
portfolio = Engine(    
         start_date= "2018-06-09", 
         portfolio= ["BABA", "PDD", "KO", "AMD","^IXIC"], 
         weights = [0.2, 0.2, 0.2, 0.2, 0.2], #equal weighting is set by default
         benchmark = ["SPY"] #SPY is set by default
)
empyrial(portfolio)

Is there any alternate way to define a portfolio, not as a list of stocks / weights but based on the value of the assets in the account?

**Comment by ssantoshp** [comment]
Hi, sorry for the late reply! I get what you mean. You cannot do that for now, however, I am working on adding this feature which would allow the user to feed the Engine with returns data from your portfolio.

**Comment by jo520iverson** [comment]
> Hi, sorry for the late reply! I get what you mean. You cannot do that for now, however, I am working on adding this feature which would allow the user to feed the Engine with returns data from your portfolio.

It would be great if we can feed return data of our portfolio as well as bechmark.

**Comment by wiener30** [comment]
It is a must-feature. Different data sources could be used.

**Comment by ssantoshp** [comment]
Definitely, will work on that this summer! Thanks for the feedback
