### ISSUE TITLE
Installation on Mac M1 Processor fails

### ISSUE THREAD

**Issue by thirumalairajr** [ssantoshp/Empyrial#76]
Pip install fails on Mac M1 chip with the error
`FileNotFoundError: [Errno 2] No such file or directory: 'README.md'` 
when it tries to install `ecos==2.0.11` 
https://github.com/embotech/ecos-python/issues/33
Workaround for this issue is to install ecos 2.0.5 version before installing empyrial
`pip install ecos==2.0.5`

@ssantoshp Can we add it to the installation docs for people using Mac M1 processor or adding this requirement in requirement.txt ?

**Comment by ssantoshp** [comment]
Thanks for reporting it, will do!
