### ISSUE TITLE
Stop Auto Rebalancing

### ISSUE THREAD

**Issue by AhmedEissa123** [ssantoshp/Empyrial#77]
How do I stop auto rebalancing?
My problem is that I found that the total cumulative return is not the weighted average of the cumulative return of each asset.

**Comment by AhmedEissa123** [comment]
I found that my calculations were wrong so I’m closing this issue.

**Comment by AhmedEissa123** [comment]
So after some other calculations, I found that some of your code is wrong (I think).
So the problem with your code is it doesn’t account properly for changing weights over time.
Since, you multiply all the returns data in the get returns function by the same weights.
While actually as the price changes for assets in the portfolio weights also change.

**Comment by ssantoshp** [comment]
Fixed in v2.1.2 of Empyrial!
