### ISSUE TITLE
Bloomberg 

### ISSUE THREAD

**Issue by Eliitas** [ssantoshp/Empyrial#80]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when X happens [...]

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Eliitas** [comment]
CAn Empiryal works  with bloomberg  API

**Comment by Nllii** [comment]
Which api specifically?

**Comment by Eliitas** [comment]
https://www.bloomberg.com/professional/support/api-library/

**Comment by Nllii** [comment]
> https://www.bloomberg.com/professional/support/api-library/

you still weren't specific?
Please see http://www.catb.org/~esr/faqs/smart-questions.html

**Comment by ssantoshp** [comment]
It doesn't directly work with it but from now on with [v2.1.3](https://github.com/ssantoshp/Empyrial/releases/tag/v2.1.3), you can use custom data! I'll be closing this issue since the question has been answered.
