### ISSUE TITLE
getting { TypeError: monthly_heatmap() missing 1 required positional argument: 'benchmark' } with any example

### ISSUE THREAD

**Issue by gigikentlight** [ssantoshp/Empyrial#83]
just run any of the examples in Spyder on a fresh Anaconda python distri running on windows 11, you'll get:
TypeError: monthly_heatmap() missing 1 required positional argument: 'benchmark'
thx

**Comment by ssantoshp** [comment]
Hey, sorry for the late reply, this is now fixed! Install the new version of Empyrial and enjoy ;)
