### ISSUE TITLE
Sharpe ratio calculation

### ISSUE THREAD

**Issue by ChengLuFred** [ssantoshp/Empyrial#9]
When I read the source code of 'Sharpe ratio' function, I found that the calculation doesn't take interest rate into account. The formula for SR is E[r - r_f] / sigma, where r_f is risk free rate. I think this would affect the accuracy of results.

**Comment by ssantoshp** [comment]
Thanks!

**Comment by ssantoshp** [comment]
Just corrected it in the new version!
